language: go

# go1.11beta1 breaks the tests for lib/net/reverseconnection
go:
    - "1.10"

before_install:
    - go get github.com/mattn/goveralls

script:
    - go test -v -covermode=count -coverprofile=coverage.out ./...
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    - make all build-darwin test
