from typing import List


class SrpcClientConfig:
    def __init__(self, host: str, port: int, cert: str, key: str) -> None: ...
    async def connect(self) -> "ConnectedSrpcClient": ...

class ConnectedSrpcClient:
    async def send_message(self, message: str) -> None: ...
    async def receive_message(self, expect_empty: bool) -> List[str]: ...
    async def send_json(self, payload: str) -> None: ...
    async def receive_json(self) -> List[str]: ...
