#! /bin/bash --posix

set -eu

endpoint='listMethods'
if [ "$1" == '-public' ]; then
    endpoint='listPublicMethods'
    shift
fi

WGET='wget -q -O -'

if [ -z "$(which wget)" ]; then
    WGET='curl'
fi
$WGET "http://$1/_goSRPC_/$endpoint" && exit
rc="$?"
echo "Error getting list of methods"
exit "$rc"
